
spring:
  data:
    rest:
      base-path: /api


  jpa:
    properties:
      hibernate:
        show_sql: false

tdrury:
  source: default
  things:
    - name: thing1
      value: 10
    - name: thing2
      value: 20