# active in all profiles
spring:
  data:
    rest:
      base-path: /api

  jpa:
    properties:
      hibernate:
        show_sql: false

---
# dev profile
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:h2:mem:sl1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=value
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true

#debug: true

